config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/about', to: 'welcome#about', as: 'about'
  resources :posts do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:index, :show] do
    resources :profiles, only: [:new, :create, :edit, :update]
    resources :blogposts, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :interests
  resources :commentlikes, only: [:create, :destroy]
  resources :postlikes, only: [:create, :destroy]
  resources :blogpostlikes, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :user_interests
  has_many :interests, through: :user_interests
  has_many :posts
  has_many :comments
  has_many :blogposts
  has_one :profile
  has_many :commentlikes
  has_many :postlikes
  has_many :blogpostlikes

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def shared_interests
    self.interests.map do |interest|
      "#{interest.user_names} share a passion for #{interest.title} with you"
    end
  end

  def display_name
    if self.profile
      if !self.profile.real_name.empty? && !self.profile.real_name.nil?
        self.profile.real_name
      else
        self.profile.alias
      end
    else
      self.email
    end
  end

  def likes?(comment)
    comment.commentlikes.find{|commentlike| commentlike.user_id == self.id} ? true : false
  end

  def likes_post?(post)
    post.postlikes.find{|postlike| postlike.user_id == self.id} ? true : false
  end

  def likes_blogpost?(blogpost)
    blogpost.blogpostlikes.find{|blogpostlike| blogpostlike.user_id == self.id} ? true: false
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     @user = User.from_omniauth(request.env["omniauth.auth"])
     sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user.profile ? @profile = @user.profile : @profile = Profile.new
    @blogposts = @user.blogposts
    @blogpost = Blogpost.new
  end

end

app/views/users/index.html.erb
<h1> Listing of member blog pages </h1>

<p> <%= @users.count %> blogs and counting! </p>

<% @users.each do |user| %>
  <% if user.profile %>
    <% if !user.profile.real_name.empty? %>
      <% name = user.profile.real_name %>
    <% else %>
      <% name = user.profile.alias %>
    <% end %>
    <%= button_to "See #{name}'s blog", user_path(user.id), method: 'get' %><br>
  <% else %>
    <%= button_to "See #{user.email} blog", user_path(user.id), method: 'get' %><br>
  <% end %>
<% end %>

<div>
  <%= render partial: '/navigation' %>
</div>

app/views/users/show.html.erb
<h1> <%= @user.display_name %> Personal Page </h1>

<%= button_to "See other member blogs", users_path, method: 'get' %>

<h3> <%= @user.display_name %>'s personal interests </h3>

<ul>
<% @user.interests.each do |interest| %>
  <li> <%= interest.title %> (<%= interest.user_names %> also share this interest) </li>
<% end %>
</ul>

<% if params[:id].to_i == current_user.id %>
  <%= button_to 'Edit your interests', '/interests', method: 'get' %><br>
<% end %>

<div>
  <% if @user.profile %>
    <h3> <%= @user.display_name %>'s profile </h3>

    <p> <%= "Birthday: #{@profile.birthday || 'No birthday shared'}" %> </p><br>

    <p> <%= "Location: #{@profile.location || 'no location shared'}" %> </p><br>

    <p> <%= "Biography: #{@profile.bio || 'No biography shared'}" %> </p><br>

    <% if params[:id].to_i == current_user.id %>
      <%= button_to "Edit Profile", edit_user_profile_path(@user.id), method: 'get' %>
    <% end %>

  <% else %>

    <%= button_to "Create your profile", new_user_profile_path(@user.id), method: 'get' %>

  <% end %>
</div>

<div>
  <% @blogposts.each do |blogpost| %>
    <h3> <%= "#{blogpost.title} (posted at: #{blogpost.created_at})" %> </h3>

    <p> <%= blogpost.body %> </p>

    <p> <%= blogpost.likes %> members like this </p>

    <div>
      <%= render partial: '/blogpostlikes', locals: {blogpost: blogpost, current_user: current_user} %>
    </div>

    <% if blogpost.user == current_user %>

      <%= button_to 'Edit Post', edit_user_blogpost_path(@user.id, blogpost.id), method: 'get' %><br>

      <%= button_to 'Delete Post', user_blogpost_path(@user.id, blogpost.id), method: 'delete' %>

    <% end %>

  <% end %>
</div>

<% if @blogpost && @blogpost.errors.any? %>
  <%= @blogpost.errors.map {|error| error.full_messages}.join %>
<% end %>

<% if params[:id].to_i == current_user.id %>
  <div>
    <h3> Make a new blogpost </h3>
    <%= form_for [@user, @blogpost] do |f| %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div><br>

      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body %>
      </div><br>

      <%= f.submit "Create Blogpost" %>
    <% end %>
  </div>
<% end %>

<div>
  <%= render partial: '/navigation' %>
</div>