config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/about', to: 'welcome#about', as: 'about'
  resources :posts do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:index, :show] do
    resources :profiles, only: [:new, :create, :edit, :update]
    resources :blogposts, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :interests
  resources :commentlikes, only: [:create, :destroy]
  resources :postlikes, only: [:create, :destroy]
  resources :blogpostlikes, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :postlikes

  validates :title, presence: true
  validates :body, presence: true

  def likes
    self.postlikes.size
  end

  def find_postlike(user)
    self.postlikes.find{|postlike| postlike.user_id == user.id}
  end

end

app/controllers/posts_controller.rb
require 'pry'
class PostsController < ApplicationController

  def index
    #binding.pry
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    #binding.pry
    @post = Post.new(title: params[:post][:title], body: params[:post][:body])
    @post.user_id = current_user.id
    if @post.save
      redirect_to '/posts'
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

end

app/views/posts/index.html.erb
<h1> Here is what we are talking about! </h1>

<span> To comment on a post, click 'Join this discussion' </span>

<% @posts.each do |post| %>
  <h3> <%= "#{post.title} [posted at #{post.created_at}]" %> </h3>
  <p> <%= post.body %> </p>
  <p> posted by: <%= post.user.display_name %> </p> <br>
  <p> <%= post.likes %> members like this </p>
  <div>
    <%= render partial: '/postlikes', locals: {post: post, current_user: current_user} %>
  </div>
  <% if post.user_id == current_user.id %>
    <%= button_to 'Delete post', post_path(post.id), method: 'delete' %><br>
  <% end %>

    <% if post.comments.last %>
      <% comment = post.comments.last %>
      <p> <strong> Latest Comment: </strong> </p>
      <p> <%= comment.user.display_name %> replied: </p>
      <p> <%= comment.body %> </p>
      <p> [At <%= comment.created_at %>] </p>
      <p> <%= comment.likes %> members like this </p>
      <div>
        <%= render partial: '/commentlikes', locals: {comment: comment, current_user: current_user} %>
      </div>
      <% if comment.user_id == current_user.id %>
        <%= button_to 'Delete comment', post_comment_path(post.id, comment.id), method: 'delete' %><br>
      <% end %>
    <% end %>

  <%= button_to "Join this discussion", post_path(post.id), method: 'get' %>

<% end %>

<p> Create a new post </p>

<%= button_to "New Post", '/posts/new', method: 'get' %>

<div>
  <%= render partial: '/navigation' %>
</div>

app/views/posts/new.html.erb
<h1> Create a new Post </h1>

<%= form_for @post do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div><br><br>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div><br><br>

  <%= f.submit %>
<% end %>


<div>
  <%= render partial: '/navigation' %>
</div>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>

<p> <%= @post.body %> </p>

<p> Posted by <%= @post.user.display_name %> on <%= @post.created_at %> </p>

<p> <%= post.likes %> members like this </p>
<div>
  <%= render partial: '/postlikes', locals: {post: @post, current_user: current_user} %>
</div>

<% if @post.comments.size == 0 %>
  <h3> No comments yet! Be the first to comment! </h3>
<% else %>
  <h3> Reply comments: </h3>

  <% @post.comments.each do |comment| %>
    <p> <strong> <%= comment.user.display_name %> said: </strong> </p>
    <p> <%= comment.body %> </p>
    <p> Commented on [ <%= comment.created_at %> ] </p>
    <div>
      <%= render partial: '/commentlikes', locals: {comment: comment, current_user: current_user} %>
    </div>
    <p> <%= comment.likes %> members like this </p>
        <% if comment.user_id == current_user.id %>
          <%= button_to 'Delete comment', post_comment_path(@post.id, comment.id), method: 'delete' %>
        <% end %>
  <% end %>
<% end %>

<h3> Write a new comment </h3>
<%= form_for [@post, @comment] do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div><br><br>

  <%= f.submit %>
<% end %>

<h3> Go back to Discussion Board </h3>

<%= button_to "Discussion Board", posts_path, method: 'get' %><br>


<div>
  <%= render partial: '/navigation' %>
</div>